# What's the name of the church?
title: Zollman Elite Cyclery
# Give a brief description of the church
description: > # this means to ignore newlines until "baseurl:"
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus blanditiis odio corrupti, 
    illum architecto consequuntur, quaerat unde repudiandae qui temporibus! Fuga maxime molestiae hic impedit 
    sit sint perferendis rerum unde.
# Leave this alone
baseurl: "" # the subpath of your site, e.g. /blog
# Change this to the domain when you are finished and ready to publish.
url: "http://elitecycleryshop.com/" # the base hostname http://elitecycleryshop.com/ & protocol for your site | Switch to "http://communitybaptistchurch.net/" Before running Glynn.  Afterwards change it back to http://localhost:4000/

# This is the path to the default images.  If you add different default images you can change them here.
default_header_image: "assets/default_header.jpg"
default_sermon_image: "assets/default_header.jpg"
default_blog_image: "assets/default_header.jpg"
default_about_image: "assets/default_header.jpg"
default_calendar_image: "assets/calendar_default.jpg"

# The lattitude and longitude for Google Maps
map_lat: "39.476286"
map_long: "-88.4009097"

# Airtable API Stuff
airtable:
  apikey: "keyRTLlrVS02vC3Vx"
  bikes: "appyFA6tctYwjAK2U"
  web: "appq8gzi9dr7LlKOc"


# LEAVE EVERYTHING ELSE ALONE!!

# Build settings
markdown: kramdown
 
# Exclude
exclude:
  - package.json
  - node_modules
  - gulpfile.js 
  - bower_components
keep_files:
  - css


# page_gen:
#   - data: 'ministries'
#     template: 'ministries'
#     name: 'name'
#     dir: 'ministries'
#   - data: 'series'
#     template: 'series'
#     name: 'title'
#     dir: 'series'
#   - data: 'sermons'
#     template: 'sermon'
#     name: 'title'
#     dir: 'sermons'
#   - data: 'blog'
#     template: 'blog-entry'
#     name: 'title'
#     dir: 'blog-posts'
#   - data: 'abouts'
#     template: 'aboutpage'
#     name: 'title'
#     dir: 'about-us'
#   - data: 'events'
#     template: 'event'
#     name: 'event_name'
#     dir: 'events'
#   - data: 'abouts'
#     template: 'about'
#     name: 'title'
#     dir: 'about-us'

ftp_host: 'biblebaptistmattoon.org'
ftp_dir: 'elitecycleryshop.com/'
ftp_passive: false
ftp_username: 'ryahay11'
ftp_password: '@88Volvocj'